# Generated by Django 3.2.9 on 2021-11-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211105_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='la',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='user',
            name='lo',
            field=models.FloatField(default=0.1),
        ),
    ]
