# Generated by Django 3.2.9 on 2021-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20211110_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('test_id', models.IntegerField()),
                ('answers', models.CharField(max_length=3000)),
            ],
        ),
    ]
