# Generated by Django 3.2.9 on 2021-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('price', models.IntegerField(db_index=True)),
                ('photo', models.ImageField(upload_to='products_icons/')),
            ],
        ),
    ]
